files:
  - source: /articles/*.md
    translation: /%original_path%/%file_name%.%two_letters_code%.md
  - source: /resources/en.toml
    translation: '"translation": "/%original_path%/%two_letters_code%.toml"'
